CREATE TABLE `Produto` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `preco` FLOAT NOT NULL,
  `descricao` VARCHAR(255),

  `categoria` VARCHAR(100),
  `marca` VARCHAR(100),
  `tamanho` VARCHAR(50),
  `genero` VARCHAR(50),

  `status` INTEGER NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;